FROM resin/raspberry-pi3-node:latest

ENV DEVICE_TYPE=%%RESIN_MACHINE_NAME%%
ENV NODE_VERSION 6.9.1
ENV RESIN_WIFI_CONNECT_VERSION 2.0.6

RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -yq --no-install-recommends \
    git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /RetroPie-Setup
RUN git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git
RUN cd RetroPie-Setup

COPY . /RetroPie-Setup

CMD ["bash"]
